; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:freenove_esp32_wrover]
platform = espressif32
board = freenove_esp32_wrover
framework = espidf

upload_speed = 2000000
monitor_speed = 115200

build_type = debug

platform_packages =
    framework-espidf @ ~3.40300.0

build_flags =
    -D MQTT_MAX_PACKET_SIZE=30000
    -D BOARD_HAS_PSRAM
    -D CONFIG_CAMERA_MODEL_ESP_EYE=1
    -D IDF_TARGET=esp32
    -D IDF_TARGET_ESP32=1
    -D CONFIG
    -D CONFIG_ESPTOOLPY_FLASHSIZE_2MB


    

    
