listener 1883
allow_anonymous true
persistence true
# Maximum size of the client write buffer
max_packet_size 65535
# Maximum number of QoS 1 and 2 messages waiting acknowledgment
max_inflight_messages 100
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout