services:
  face_recognition_service:
    build:
      context: .
      dockerfile: ./service/Dockerfile
    container_name: face_recognition_service
    ports:
      - "5001:5001"
    volumes:
      - ./core:/app/core
      - ./service:/app/service
      - ./config:/app/config
      - ./core/models:/app/core/models
    environment:
      - MODEL_PATH=/app/core/models/ghostfacenets.h5
      - PYTHONPATH=/app
    restart: unless-stopped